#!/usr/bin/env node

'use strict';

require('babel-register')({ presets:[ 'skypager' ] })

const colors = require('colors')
const figlet = require('figlet')
const argv = require('minimist')(process.argv)
const log = console.log.bind(console)
const skypagerRepl = require('./index')

log()
log(colors.rainbow(figlet.textSync('Skypager')))
log()
log()

skypagerRepl.start({icon:'rocket'}, global, (err, repl) => {
  if (err || !repl) {
    log('There was an error', err)
  }
})
